export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const CLEAR_ONE_PRODUCT = "CLEAR_ONE_PRODUCT";
